staging: &default              
  adapter: postgresql
  encoding: unicode
  database: etl_staging
  pool: 5
  host: localhost
  username: postgres

development:
  <<: *default 
  database: etl_development

test:
  <<: *default 
  database: etl_test
